-- Fate_Qin_Fix
-- Author: HaoJun0823
-- DateCreated: 9/7/2021 6:55:32 PM
--------------------------------------------------------------

INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES 
("FATE_QIN_FIRST_EMPEROR_TRAIT", "TRAIT_FATE_QIN_CITY_RELIGION_ADJUST_RELIGIOUS_SPREAD_STRENGTH");

INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
("TRAIT_FATE_QIN_CITY_RELIGION_ADJUST_RELIGIOUS_SPREAD_STRENGTH", "MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER", 0, 0, 0, "REQUIREMENT_SET_FATE_QIN_PLAYER_HAS_TARGET_RESOURCE_FOR_RELIGIOUS", NULL);

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
("TRAIT_FATE_QIN_CITY_RELIGION_ADJUST_RELIGIOUS_SPREAD_STRENGTH", "ModifierId", "MODIFIER_FATE_QIN_FIX_RELIGIOUS");


INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
("MODIFIER_FATE_QIN_FIX_RELIGIOUS", "MODIFIER_SINGLE_CITY_RELIGIOUS_SPREADS", 0, 0, 0, NULL, NULL);

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
("MODIFIER_FATE_QIN_FIX_RELIGIOUS", "Amount", 200);


INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES 
("FATE_QIN_FIRST_EMPEROR_TRAIT", "TRAIT_FATE_QIN_CITY_RELIGION_ADJUST_RELIGIOUS_SPREAD_STRENGTH_RADIO");

INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
("TRAIT_FATE_QIN_CITY_RELIGION_ADJUST_RELIGIOUS_SPREAD_STRENGTH_RADIO", "MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER", 0, 0, 0, "REQUIREMENT_SET_FATE_QIN_PLAYER_HAS_TARGET_RESOURCE_FOR_RELIGIOUS_RADIO", NULL);

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
("TRAIT_FATE_QIN_CITY_RELIGION_ADJUST_RELIGIOUS_SPREAD_STRENGTH_RADIO", "ModifierId", "MODIFIER_FATE_QIN_FIX_RELIGIOUS_RADIO");


INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
("MODIFIER_FATE_QIN_FIX_RELIGIOUS_RADIO", "MODIFIER_SINGLE_CITY_RELIGIOUS_SPREADS", 0, 0, 0, NULL, NULL);

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
("MODIFIER_FATE_QIN_FIX_RELIGIOUS_RADIO", "Amount", 200);





INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES 
("FATE_QIN_FIRST_EMPEROR_TRAIT", "TRAIT_FATE_QIN_ZONE_X_UNIT_FIX");

INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
("TRAIT_FATE_QIN_ZONE_X_UNIT_FIX", "MODIFIER_PLAYER_DISTRICT_CREATE_UNIT", 1, 0, 0, "REQUIREMENT_SET_FATE_QIN_PLAYER_GREAT_PERSON_WITH_TECH", NULL);

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
("TRAIT_FATE_QIN_ZONE_X_UNIT_FIX", "DistrictType", "DISTRICT_INDUSTRIAL_ZONE_FATE_QIN_X"), 
("TRAIT_FATE_QIN_ZONE_X_UNIT_FIX", "UnitType", "UNIT_FATE_QIN_CHINESE_CROUCHING_TIGER");
